// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {solver} from '../models';

export function Addition(arg1:number,arg2:number):Promise<number>;

export function CancelGeneration():Promise<void>;

export function ClearData():Promise<void>;

export function CreateAvailability(arg1:models.Availability):Promise<number|models.ValidationResult>;

export function CreateEmployee(arg1:models.Employee):Promise<number>;

export function CreateSchedule(arg1:models.Schedule):Promise<number>;

export function CreateShift(arg1:models.Shift):Promise<number|models.ValidationResult>;

export function DeleteAvailability(arg1:number):Promise<void>;

export function DeleteEmployee(arg1:number):Promise<void>;

export function DeleteSchedule(arg1:number):Promise<void>;

export function DeleteShift(arg1:number):Promise<void>;

export function DeleteShiftsBySchedule(arg1:number):Promise<void>;

export function GenerateSchedule(arg1:number):Promise<solver.SolverResult>;

export function GetAllAvailabilities():Promise<Array<models.Availability>>;

export function GetAllDaySettings():Promise<Record<number, models.DaySettings>>;

export function GetAllEmployees():Promise<Array<models.Employee>>;

export function GetAllSchedules():Promise<Array<models.Schedule>>;

export function GetAvailabilityByEmployee(arg1:number):Promise<Array<models.Availability>>;

export function GetDaySettings(arg1:number):Promise<models.DaySettings>;

export function GetScheduleByWeek(arg1:string):Promise<models.Schedule>;

export function GetSettings():Promise<models.Settings>;

export function GetShiftsByEmployee(arg1:number):Promise<Array<models.Shift>>;

export function GetShiftsBySchedule(arg1:number):Promise<Array<models.Shift>>;

export function Greet(arg1:string):Promise<string>;

export function Seed():Promise<void>;

export function UpdateAvailability(arg1:models.Availability):Promise<models.ValidationResult>;

export function UpdateDaySettings(arg1:models.DaySettings):Promise<void>;

export function UpdateEmployee(arg1:models.Employee):Promise<void>;

export function UpdateSchedule(arg1:models.Schedule):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateShift(arg1:models.Shift):Promise<models.ValidationResult>;
