// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Addition(arg1:number,arg2:number):Promise<number>;

export function ClearData():Promise<void>;

export function CreateEmployee(arg1:models.Employee):Promise<number>;

export function DeleteEmployee(arg1:number):Promise<void>;

export function GetAllEmployees():Promise<Array<models.Employee>>;

export function Greet(arg1:string):Promise<string>;

export function Seed():Promise<void>;

export function UpdateEmployee(arg1:models.Employee):Promise<void>;
